# -*- coding: utf-8 -*-

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/Tangut_NLP

"""

# -*- coding: utf-8 -*-
"""tangut_base_derived_inheritance.ipynb
"""

# ============================================================
# Cell 0: Imports & Global Configuration
# ============================================================
import os, json, math, pickle, random
from collections import Counter, defaultdict
from itertools import combinations

import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, f1_score, roc_auc_score, RocCurveDisplay
from scipy.stats import ttest_ind, chi2
from tqdm import tqdm
import matplotlib.pyplot as plt
import matplotlib
import seaborn as sns

matplotlib.rcParams['font.family'] = ['DejaVu Sans']
matplotlib.rcParams['axes.unicode_minus'] = False

# Reproducibility
SEED = 42
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)
torch.cuda.manual_seed_all(SEED)

# Device
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f'Device: {device}')
print(f'PyTorch: {torch.__version__}')
if torch.cuda.is_available():
    print(f'GPU: {torch.cuda.get_device_name(0)}')
    print(f'Memory: {torch.cuda.get_device_properties(0).total_memory / 1e9:.1f} GB')

# Paths
BASE_PATH = '/content/drive/MyDrive/SCI_Journal'


# ============================================================
# Google Drive Remount
# ============================================================
import shutil
from google.colab import drive

if os.path.exists('/content/drive'):
    shutil.rmtree('/content/drive')
    print('Removed residual /content/drive')

drive.mount('/content/drive')
print('Drive remounted successfully')

OUTPUT_DIR = os.path.join(BASE_PATH, 'base_derived_inheritance')
os.makedirs(OUTPUT_DIR, exist_ok=True)
print(f'Output directory: {OUTPUT_DIR}')

sci = '/content/drive/MyDrive/SCI_Journal'
print(f'\n=== {sci} directory contents ===')
for item in sorted(os.listdir(sci)):
    print(f'  {item}')


# ============================================================
# Cell 1: Stage 1 — Vocabulary Expansion + MLM Pretraining
# ============================================================

MLM_OUTPUT_DIR = os.path.join(BASE_PATH, 'bert_wwm_ext_tangut_mlm')
STAGE1_DONE = os.path.exists(os.path.join(MLM_OUTPUT_DIR, 'pytorch_model.bin')) or \
              os.path.exists(os.path.join(MLM_OUTPUT_DIR, 'model.safetensors'))

if STAGE1_DONE:
    print('Stage 1 already completed. Skipping...')
    print(f'   Model directory: {MLM_OUTPUT_DIR}')
else:
    print('=' * 60)
    print('STAGE 1: Vocabulary Expansion + MLM Pretraining')
    print('=' * 60)

    from transformers import (
        BertTokenizer, BertForMaskedLM, BertConfig,
        Trainer, TrainingArguments, DataCollatorForLanguageModeling
    )
    from datasets import Dataset as HFDataset

    BASE_MODEL = 'hfl/chinese-bert-wwm-ext'

    # --- Load training texts ---
    print('\n--- Loading training texts ---')
    for fname in ['sentence_pairs.txt', 'word_pairs.txt', 'dictionary.txt', 'pure_tangut.txt']:
        fp = os.path.join(BASE_PATH, fname)
        print(f'  {fname}: exists={os.path.exists(fp)}, size={os.path.getsize(fp) if os.path.exists(fp) else "N/A"}')

    import glob
    all_files = glob.glob(os.path.join(BASE_PATH, '*'))
    print(f'\n  All files in BASE_PATH ({len(all_files)} total):')
    for f in sorted(all_files):
        print(f'    {os.path.basename(f)} ({os.path.getsize(f)} bytes)')

    texts = []

    sp_path = os.path.join(BASE_PATH, 'sentence_pairs.txt')
    if os.path.exists(sp_path):
        with open(sp_path, 'r', encoding='utf-8') as f:
            for line in f:
                line = line.strip()
                if not line:
                    continue
                if '\t' in line:
                    tangut, meaning = line.split('\t', 1)
                    if len(tangut) > 0 and len(meaning.strip()) > 0:
                        texts.append(' '.join(list(tangut)) + ' [SEP] ' + meaning.strip())
                else:
                    texts.append(line)
        print(f'  sentence_pairs.txt: {len(texts)} lines')

    wp_path = os.path.join(BASE_PATH, 'word_pairs.txt')
    if os.path.exists(wp_path):
        n_before = len(texts)
        with open(wp_path, 'r', encoding='utf-8') as f:
            for line in f:
                line = line.strip()
                if line:
                    texts.append(line)
        print(f'  word_pairs.txt: {len(texts) - n_before} lines')

    dict_path = os.path.join(BASE_PATH, 'dictionary.txt')
    if os.path.exists(dict_path):
        n_before = len(texts)
        with open(dict_path, 'r', encoding='utf-8') as f:
            for line in f:
                line = line.strip()
                if line and '\t' in line:
                    texts.append(line.replace('\t', '：'))
        print(f'  dictionary.txt: {len(texts) - n_before} lines')

    pt_path = os.path.join(BASE_PATH, 'pure_tangut.txt')
    if os.path.exists(pt_path):
        n_before = len(texts)
        with open(pt_path, 'r', encoding='utf-8') as f:
            for line in f:
                line = line.strip()
                if line:
                    texts.append(line)
        print(f'  pure_tangut.txt: {len(texts) - n_before} lines')

    print(f'  Total texts: {len(texts)}')

    if len(texts) == 0:
        raise ValueError('No training texts loaded! Stage 1 cannot proceed.')

    # --- Expand vocabulary ---
    print('\n--- Expanding vocabulary ---')
    original_tokenizer = BertTokenizer.from_pretrained(BASE_MODEL)
    original_vocab = original_tokenizer.get_vocab()
    print(f'  Original vocab size: {len(original_vocab)}')

    tangut_chars = set()
    for text in texts:
        for ch in text:
            cp = ord(ch)
            if (0x17000 <= cp <= 0x187FF) or (0x18800 <= cp <= 0x18AFF):
                tangut_chars.add(ch)
    print(f'  Tangut characters found: {len(tangut_chars)}')

    new_tokens = [ch for ch in sorted(tangut_chars) if ch not in original_vocab]
    print(f'  New tokens to add: {len(new_tokens)}')
    original_tokenizer.add_tokens(new_tokens)
    print(f'  Expanded vocab size: {len(original_tokenizer)}')

    # --- Resize model embeddings ---
    print('\n--- Resizing model embeddings ---')
    model = BertForMaskedLM.from_pretrained(BASE_MODEL)
    model.resize_token_embeddings(len(original_tokenizer))
    print(f'  Model embedding size: {model.get_input_embeddings().weight.shape}')

    # --- Tokenize and create dataset ---
    print('\n--- Tokenizing ---')
    tokenized = original_tokenizer(
        texts,
        truncation=True,
        padding='max_length',
        max_length=128,
        return_tensors='np'
    )
    hf_dataset = HFDataset.from_dict({
        'input_ids': tokenized['input_ids'].tolist(),
        'attention_mask': tokenized['attention_mask'].tolist(),
    })
    print(f'  Dataset: {len(hf_dataset)} samples')

    # --- MLM Training ---
    print('\n--- MLM Pretraining (30 epochs) ---')
    data_collator = DataCollatorForLanguageModeling(
        tokenizer=original_tokenizer, mlm=True, mlm_probability=0.15
    )

    training_args = TrainingArguments(
        output_dir=MLM_OUTPUT_DIR,
        overwrite_output_dir=True,
        num_train_epochs=30,
        per_device_train_batch_size=16,
        gradient_accumulation_steps=2,
        learning_rate=2e-5,
        warmup_steps=500,
        weight_decay=0.01,
        logging_steps=100,
        save_steps=500,
        save_total_limit=2,
        fp16=torch.cuda.is_available(),
        dataloader_num_workers=2,
        report_to='none',
    )

    trainer = Trainer(
        model=model,
        args=training_args,
        data_collator=data_collator,
        train_dataset=hf_dataset,
    )
    trainer.train()

    model.save_pretrained(MLM_OUTPUT_DIR)
    original_tokenizer.save_pretrained(MLM_OUTPUT_DIR)
    print(f'\nStage 1 complete. Model saved to {MLM_OUTPUT_DIR}')

    del model, trainer, tokenized, hf_dataset
    torch.cuda.empty_cache()

# ============================================================
# Verify Stage 1 output
# ============================================================
from transformers import BertTokenizerFast, BertModel

if os.path.exists(MLM_OUTPUT_DIR):
    mlm_tokenizer = BertTokenizerFast.from_pretrained(MLM_OUTPUT_DIR)
    print(f'Tokenizer loaded from MLM: {len(mlm_tokenizer)} tokens')
else:
    raise FileNotFoundError(f'MLM output directory not found: {MLM_OUTPUT_DIR}')


# ============================================================
# Cell 2: Data Loading
# ============================================================

def load_component_jsonl(filepath):
    records = []
    with open(filepath, 'r', encoding='utf-8') as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            obj = json.loads(line)
            records.append({
                'char': obj.get('char', ''),
                'components': obj.get('components', []),
                'comp_types': obj.get('comp_types', []),
                'sheng_lei': obj.get('sheng_lei', ''),
                'sheng_lei_is_multi': obj.get('sheng_lei_is_multi', False),
                'source': obj.get('source', '')
            })
    return pd.DataFrame(records)

print('Loading component data...')
comp_file = os.path.join(BASE_PATH, 'tangut_sheng_lei.jsonl')
df_components = load_component_jsonl(comp_file)
print(f'Component data: {len(df_components)} entries')

dict_file = os.path.join(BASE_PATH, 'dictionary.txt')
char_to_def = {}
if os.path.exists(dict_file):
    df_dict = pd.read_csv(dict_file, sep='\t', header=None,
                          names=['char', 'definition'], encoding='utf-8')
    df_dict = df_dict.dropna(subset=['definition'])
    df_dict = df_dict[df_dict['definition'].str.strip() != '']
    for _, row in df_dict.iterrows():
        ch = row['char']
        definition = row['definition']
        if ch not in char_to_def:
            char_to_def[ch] = definition
    print(f'Dictionary: {len(df_dict)} entries, {len(char_to_def)} unique chars with definitions')
else:
    print('WARNING: dictionary.txt not found.')

# ============================================================
# Cell 2b: Collect all components
# ============================================================
print('\n--- Collecting all components ---')
all_components_set = set()
for comps in df_components['components']:
    all_components_set.update(comps)

component_pkl_path = os.path.join(BASE_PATH, 'component.pkl')
if os.path.exists(component_pkl_path):
    with open(component_pkl_path, 'rb') as f:
        component_dict_pkl = pickle.load(f)
    for comps in component_dict_pkl.values():
        all_components_set.update(comps)
    print(f'Added components from component.pkl: total {len(all_components_set)}')

print(f'Total unique components: {len(all_components_set)}')

# ============================================================
# Cell 2c: Basic Character Identification (Atomic + Compound)
# ============================================================
print('\n--- Basic Character Identification ---')

comp_freq = Counter()
for comps in df_components['components']:
    comp_freq.update(comps)

BASIC_CHAR_MIN_FREQ = 20
basic_char_set = {comp for comp, freq in comp_freq.items() if freq >= BASIC_CHAR_MIN_FREQ}
print(f'Atomic basic characters (freq >= {BASIC_CHAR_MIN_FREQ}): {len(basic_char_set)}')

# Compound Basic Characters
COMPOUND_MIN_FREQ = 5
df_valid_basic = df_components[
    df_components['sheng_lei'].apply(lambda x: isinstance(x, str) and x != '' and x != '0')
].copy()
df_valid_basic = df_valid_basic[df_valid_basic['components'].apply(len) > 0].copy()

all_comp_seqs = df_valid_basic['components'].tolist()
subseq_count = defaultdict(int)
for comps in all_comp_seqs:
    n = len(comps)
    seen_in_this_char = set()
    for length in range(2, n + 1):
        for indices in combinations(range(n), length):
            subseq = tuple(comps[i] for i in indices)
            if subseq not in seen_in_this_char:
                subseq_count[subseq] += 1
                seen_in_this_char.add(subseq)

compound_basic_seqs = {seq: cnt for seq, cnt in subseq_count.items() if cnt >= COMPOUND_MIN_FREQ}
print(f'Compound basic chars (freq >= {COMPOUND_MIN_FREQ}): {len(compound_basic_seqs)}')

def find_compound_basic_in_char(comps, compound_basic_seqs):
    matches = []
    n = len(comps)
    for length in range(2, n + 1):
        for indices in combinations(range(n), length):
            subseq = tuple(comps[i] for i in indices)
            if subseq in compound_basic_seqs:
                matches.append(indices)
    return matches


# ============================================================
# Cell 3: Data Preprocessing
# ============================================================
print('\n' + '=' * 60)
print('DATA PREPROCESSING')
print('=' * 60)

df_valid = df_components[
    df_components['sheng_lei'].apply(lambda x: isinstance(x, str) and x != '' and x != '0')
].copy()
df_valid = df_valid[df_valid['components'].apply(len) > 0].copy()
print(f'Valid entries: {len(df_valid)}')

sheng_lei_classes = sorted(df_valid['sheng_lei'].unique())
sheng_lei2id = {cls: i for i, cls in enumerate(sheng_lei_classes)}
id2sheng_lei = {i: cls for cls, i in sheng_lei2id.items()}
NUM_PHONETIC_CLASSES = len(sheng_lei_classes)
print(f'Phonetic classes: {NUM_PHONETIC_CLASSES}')

component2id = {'<PAD>': 0, '<UNK>': 1}
for comp in sorted(all_components_set):
    if comp not in component2id:
        component2id[comp] = len(component2id)
COMP_VOCAB_SIZE = len(component2id)
print(f'Component vocabulary: {COMP_VOCAB_SIZE}')

char2id = {'<PAD>': 0, '<UNK>': 1}
for char in df_valid['char'].unique():
    if char not in char2id:
        char2id[char] = len(char2id)
CHAR_VOCAB_SIZE = len(char2id)
print(f'Character vocabulary: {CHAR_VOCAB_SIZE}')

def encode_sample(row):
    char = row['char']
    char_id = char2id.get(char, char2id['<UNK>'])
    comp_ids = [component2id.get(c, component2id['<UNK>']) for c in row['components']]
    n_comps = len(comp_ids)
    is_basic = [1 if c in basic_char_set else 0 for c in row['components']]
    compound_matches = find_compound_basic_in_char(row['components'], compound_basic_seqs)
    is_compound_basic = [0] * n_comps
    for idx_tuple in compound_matches:
        for j in idx_tuple:
            is_compound_basic[j] = 1
    phonetic_label = sheng_lei2id[row['sheng_lei']]
    definition = char_to_def.get(char, '')
    has_definition = 1 if definition else 0

    return {
        'char': char,
        'char_id': char_id,
        'comp_ids': comp_ids,
        'comp_chars': row['components'],
        'is_basic': is_basic,
        'is_compound_basic': is_compound_basic,
        'phonetic_label': phonetic_label,
        'sheng_lei': row['sheng_lei'],
        'definition': definition,
        'has_definition': has_definition,
    }

encoded_data = [encode_sample(row) for _, row in df_valid.iterrows()]
print(f'Encoded samples: {len(encoded_data)}')


# ============================================================
# Cell 4: Definition Embedding Pre-computation
# ============================================================
print('\n' + '=' * 60)
print('DEFINITION EMBEDDING PRE-COMPUTATION')
print('=' * 60)

DEF_EMBEDDING_DIM = 768

if char_to_def:
    from transformers import BertModel, BertTokenizer
    print('Loading Chinese BERT for definition encoding...')
    def_bert = BertModel.from_pretrained('hfl/chinese-bert-wwm-ext')
    def_tokenizer = BertTokenizer.from_pretrained('hfl/chinese-bert-wwm-ext')
    def_bert = def_bert.to(device)
    def_bert.eval()

    unique_defs = list(set(char_to_def.values()))
    print(f'Unique definitions: {len(unique_defs)}')

    def_to_embedding = {}
    batch_size = 64
    with torch.no_grad():
        for i in tqdm(range(0, len(unique_defs), batch_size), desc='Encoding definitions'):
            batch_defs = unique_defs[i:i+batch_size]
            enc = def_tokenizer(batch_defs, padding=True, truncation=True,
                               max_length=64, return_tensors='pt')
            enc = {k: v.to(device) for k, v in enc.items()}
            outputs = def_bert(**enc)
            cls_emb = outputs.last_hidden_state[:, 0, :]
            cls_emb = F.normalize(cls_emb, dim=1)
            for j, definition in enumerate(batch_defs):
                def_to_embedding[definition] = cls_emb[j].cpu()

    print(f'Encoded {len(def_to_embedding)} unique definitions')

    char_to_def_emb = {}
    for ch, definition in char_to_def.items():
        if definition in def_to_embedding:
            char_to_def_emb[ch] = def_to_embedding[definition]
    print(f'char_to_def_emb: {len(char_to_def_emb)} characters')

    del def_bert, def_tokenizer
    torch.cuda.empty_cache()
else:
    char_to_def_emb = {}
    print('char_to_def_emb is empty.')

print('\n--- Building BERT input sequences ---')
STAGE1_TOKENIZER_PATH = os.path.join(BASE_PATH, 'bert_wwm_ext_tangut_mlm')
bert_tokenizer = BertTokenizer.from_pretrained(STAGE1_TOKENIZER_PATH)
print(f'Tokenizer vocab size: {len(bert_tokenizer)}')

BERT_MAX_LENGTH = 4

def build_bert_input(char):
    input_text = char
    enc = bert_tokenizer(
        input_text,
        padding='max_length',
        truncation=True,
        max_length=BERT_MAX_LENGTH,
        return_tensors='pt'
    )
    return {
        'input_ids': enc['input_ids'].squeeze(0),
        'attention_mask': enc['attention_mask'].squeeze(0),
    }

for sample in tqdm(encoded_data, desc='Building BERT inputs'):
    bert_enc = build_bert_input(sample['char'])
    sample['bert_input_ids'] = bert_enc['input_ids']
    sample['bert_attention_mask'] = bert_enc['attention_mask']

MAX_COMPONENTS = 10


# ============================================================
# Cell 5: Build Base-Derived Character Relationships
# ============================================================
print('\n' + '=' * 60)
print('BUILDING BASE-DERIVED CHARACTER RELATIONSHIPS')
print('=' * 60)

def semantic_similarity(char_a, char_b, char_to_def_emb):
    emb_a = char_to_def_emb.get(char_a)
    emb_b = char_to_def_emb.get(char_b)
    if emb_a is None or emb_b is None:
        return None
    return F.cosine_similarity(emb_a.unsqueeze(0), emb_b.unsqueeze(0)).item()


base_derived_pairs = []

for char_b in encoded_data:
    comps_b_set = set(char_b['comp_ids'])
    for char_a in encoded_data:
        if char_a['char'] == char_b['char']:
            continue

        comps_a_set = set(char_a['comp_ids'])

        if comps_a_set.issubset(comps_b_set) and len(comps_a_set) < len(comps_b_set):
            pair_key = (char_a['char'], char_b['char'])
            if pair_key in pair_chars_seen:
                continue
            pair_chars_seen.add(pair_key)

            phonetic_inherited = (char_a['phonetic_label'] == char_b['phonetic_label'])

            sim = semantic_similarity(char_a['char'], char_b['char'], char_to_def_emb)

            added_comps = list(comps_b_set - comps_a_set)
            added_comp_chars = []
            for cid in added_comps:
                id2comp = {v: k for k, v in component2id.items()}
                added_comp_chars.append(id2comp.get(cid, f'[{cid}]'))

            comps_a_tuple = tuple(sorted(char_a['comp_ids']))
            is_compound_base = comps_a_tuple in compound_basic_seqs

            base_derived_pairs.append({
                'base_char': char_a['char'],
                'base_char_id': char_a['char_id'],
                'base_comps': char_a['comp_chars'],
                'base_comp_ids': char_a['comp_ids'],
                'base_sheng_lei': char_a['sheng_lei'],
                'base_phonetic_label': char_a['phonetic_label'],
                'base_definition': char_a['definition'],
                'base_has_def': char_a['has_definition'],
                'base_bert_input_ids': char_a['bert_input_ids'],
                'base_bert_attention_mask': char_a['bert_attention_mask'],
                'base_is_basic': char_a['is_basic'],
                'base_is_compound_basic': char_a['is_compound_basic'],

                'derived_char': char_b['char'],
                'derived_char_id': char_b['char_id'],
                'derived_comps': char_b['comp_chars'],
                'derived_comp_ids': char_b['comp_ids'],
                'derived_sheng_lei': char_b['sheng_lei'],
                'derived_phonetic_label': char_b['phonetic_label'],
                'derived_definition': char_b['definition'],
                'derived_has_def': char_b['has_definition'],
                'derived_bert_input_ids': char_b['bert_input_ids'],
                'derived_bert_attention_mask': char_b['bert_attention_mask'],
                'derived_is_basic': char_b['is_basic'],
                'derived_is_compound_basic': char_b['is_compound_basic'],

                'added_comps': added_comp_chars,
                'added_comp_ids': added_comps,
                'phonetic_inherited': phonetic_inherited,
                'semantic_similarity': sim,
                'is_compound_base': is_compound_base,
                'base_comp_count': len(comps_a_set),
                'derived_comp_count': len(comps_b_set),
            })

print(f'Total base-derived pairs: {len(base_derived_pairs)}')

phonetic_inherit_rate = sum(1 for p in base_derived_pairs if p['phonetic_inherited']) / len(base_derived_pairs)
print(f'\nPhonetic inheritance rate: {phonetic_inherit_rate:.4f} '
      f'({sum(1 for p in base_derived_pairs if p["phonetic_inherited"])}/{len(base_derived_pairs)})')

pairs_with_sem = [p for p in base_derived_pairs if p['semantic_similarity'] is not None]
if pairs_with_sem:
    avg_sem_sim = np.mean([p['semantic_similarity'] for p in pairs_with_sem])
    print(f'Average semantic similarity: {avg_sem_sim:.4f} ({len(pairs_with_sem)} pairs with definition)')

print('\n--- Phonetic Inheritance by Base Type ---')
for is_compound in [True, False]:
    subset = [p for p in base_derived_pairs if p['is_compound_base'] == is_compound]
    if subset:
        rate = sum(1 for p in subset if p['phonetic_inherited']) / len(subset)
        print(f'  {"Compound" if is_compound else "Atomic"} base: {rate:.4f} ({len(subset)} pairs)')

print('\n--- Phonetic Inheritance by Number of Added Components ---')
added_counts = sorted(set(p['derived_comp_count'] - p['base_comp_count'] for p in base_derived_pairs))
for n_added in added_counts:
    subset = [p for p in base_derived_pairs if p['derived_comp_count'] - p['base_comp_count'] == n_added]
    if subset:
        rate = sum(1 for p in subset if p['phonetic_inherited']) / len(subset)
        print(f'  +{n_added} component(s): {rate:.4f} ({len(subset)} pairs)')


# ============================================================
# Cell 6: Semantic (Form) Inheritance Analysis
# ============================================================
print('\n' + '=' * 60)
print('SEMANTIC INHERITANCE ANALYSIS')
print('=' * 60)

if pairs_with_sem:
    inherited_sim = [p['semantic_similarity'] for p in pairs_with_sem if p['phonetic_inherited']]
    not_inherited_sim = [p['semantic_similarity'] for p in pairs_with_sem if not p['phonetic_inherited']]

    print(f'  Phonetic inherited: mean sim={np.mean(inherited_sim):.4f} (n={len(inherited_sim)})')
    print(f'  Phonetic NOT inherited: mean sim={np.mean(not_inherited_sim):.4f} (n={len(not_inherited_sim)})')

    t_stat, p_val = ttest_ind(inherited_sim, not_inherited_sim)
    sig = '***' if p_val < 0.001 else '**' if p_val < 0.01 else '*' if p_val < 0.05 else 'ns'
    print(f'  t-test: t={t_stat:.4f}, p={p_val:.4f} {sig}')

    high_sim_threshold = 0.5
    quadrants = {
        'phonetic_yes_sem_yes': 0,
        'phonetic_yes_sem_no': 0,
        'phonetic_no_sem_yes': 0,
        'phonetic_no_sem_no': 0,
    }
    for p in pairs_with_sem:
        if p['phonetic_inherited'] and p['semantic_similarity'] >= high_sim_threshold:
            quadrants['phonetic_yes_sem_yes'] += 1
        elif p['phonetic_inherited'] and p['semantic_similarity'] < high_sim_threshold:
            quadrants['phonetic_yes_sem_no'] += 1
        elif not p['phonetic_inherited'] and p['semantic_similarity'] >= high_sim_threshold:
            quadrants['phonetic_no_sem_yes'] += 1
        else:
            quadrants['phonetic_no_sem_no'] += 1

    total = sum(quadrants.values())
    print(f'\n--- Phonetic vs. Semantic Quadrant Analysis ---')
    print(f'  Both inherited:     {quadrants["phonetic_yes_sem_yes"]:>4}/{total} '
          f'({quadrants["phonetic_yes_sem_yes"]/total*100:.1f}%)')
    print(f'  Only phonetic:      {quadrants["phonetic_yes_sem_no"]:>4}/{total} '
          f'({quadrants["phonetic_yes_sem_no"]/total*100:.1f}%)')
    print(f'  Only semantic:      {quadrants["phonetic_no_sem_yes"]:>4}/{total} '
          f'({quadrants["phonetic_no_sem_yes"]/total*100:.1f}%)')
    print(f'  Neither:            {quadrants["phonetic_no_sem_no"]:>4}/{total} '
          f'({quadrants["phonetic_no_sem_no"]/total*100:.1f}%)')
else:
    print('  No definition data available, skipping semantic analysis.')


# ============================================================
# Cell 7: Dataset Split & Dataset Class
# ============================================================
print('\n' + '=' * 60)
print('DATASET SPLIT')
print('=' * 60)

SEMANTIC_THRESHOLD = 0.5

valid_pairs = []
for p in base_derived_pairs:
    has_bert = ('base_bert_input_ids' in p and 'derived_bert_input_ids' in p)
    if has_bert:
        if p['semantic_similarity'] is not None:
            semantic_label = 1 if p['semantic_similarity'] >= SEMANTIC_THRESHOLD else 0
        else:
        valid_pairs.append({
            **p,
            'phonetic_label': 1 if p['phonetic_inherited'] else 0,
            'semantic_label': semantic_label,
        })

print(f'Valid pairs for model: {len(valid_pairs)}')

unique_base_derived = list(set((p['base_char'], p['derived_char']) for p in valid_pairs))
train_pairs, temp_pairs = train_test_split(unique_base_derived, test_size=0.3, random_state=SEED)
val_pairs, test_pairs = train_test_split(temp_pairs, test_size=0.5, random_state=SEED)

train_set = set(train_pairs)
val_set = set(val_pairs)
test_set = set(test_pairs)

train_data = [p for p in valid_pairs if (p['base_char'], p['derived_char']) in train_set]
val_data = [p for p in valid_pairs if (p['base_char'], p['derived_char']) in val_set]
test_data = [p for p in valid_pairs if (p['base_char'], p['derived_char']) in test_set]

print(f'Train: {len(train_data)}, Val: {len(val_data)}, Test: {len(test_data)}')

train_phonetic_rate = sum(p['phonetic_label'] for p in train_data) / len(train_data)
val_phonetic_rate = sum(p['phonetic_label'] for p in val_data) / len(val_data)
test_phonetic_rate = sum(p['phonetic_label'] for p in test_data) / len(test_data)
print(f'Phonetic inheritance rate: Train={train_phonetic_rate:.4f}, Val={val_phonetic_rate:.4f}, Test={test_phonetic_rate:.4f}')

train_semantic_rate = sum(p['semantic_label'] for p in train_data) / len(train_data)
val_semantic_rate = sum(p['semantic_label'] for p in val_data) / len(val_data)
test_semantic_rate = sum(p['semantic_label'] for p in test_data) / len(test_data)
print(f'Semantic inheritance rate: Train={train_semantic_rate:.4f}, Val={val_semantic_rate:.4f}, Test={test_semantic_rate:.4f}')

# ============================================================
# Dataset Class
# ============================================================
class BaseDerivedDataset(Dataset):

    def __init__(self, data, max_components=MAX_COMPONENTS):
        self._data = data
        self._max_components = max_components

    def __len__(self):
        return len(self._data)

    def __getitem__(self, idx):
        p = self._data[idx]

        base_comp_ids = list(p['base_comp_ids'])
        base_comp_len = len(base_comp_ids)
        base_pad_len = self._max_components - base_comp_len

        derived_comp_ids = list(p['derived_comp_ids'])
        derived_comp_len = len(derived_comp_ids)
        derived_pad_len = self._max_components - derived_comp_len

        return {
            'base_bert_input_ids': p['base_bert_input_ids'].clone(),
            'base_bert_attention_mask': p['base_bert_attention_mask'].clone(),
            'base_comp_ids': torch.tensor(base_comp_ids + [0] * base_pad_len, dtype=torch.long),
            'base_comp_mask': torch.tensor([1] * base_comp_len + [0] * base_pad_len, dtype=torch.float),

            'derived_bert_input_ids': p['derived_bert_input_ids'].clone(),
            'derived_bert_attention_mask': p['derived_bert_attention_mask'].clone(),
            'derived_comp_ids': torch.tensor(derived_comp_ids + [0] * derived_pad_len, dtype=torch.long),
            'derived_comp_mask': torch.tensor([1] * derived_comp_len + [0] * derived_pad_len, dtype=torch.float),

            'phonetic_label': torch.tensor(p['phonetic_label'], dtype=torch.float),
            'semantic_label': torch.tensor(p['semantic_label'], dtype=torch.float),
        }

BATCH_SIZE = 32

train_dataset = BaseDerivedDataset(train_data)
val_dataset = BaseDerivedDataset(val_data)
test_dataset = BaseDerivedDataset(test_data)

train_loader = DataLoader(train_dataset, batch_size=BATCH_SIZE, shuffle=True)
val_loader = DataLoader(val_dataset, batch_size=BATCH_SIZE, shuffle=False)
test_loader = DataLoader(test_dataset, batch_size=BATCH_SIZE, shuffle=False)

print(f'\nDataloaders created: Train={len(train_loader)} batches, Val={len(val_loader)} batches, Test={len(test_loader)} batches')


# ============================================================
# Cell 8: Dual Encoder Inheritance Model
# ============================================================
print('\n' + '=' * 60)
print('MODEL DEFINITION')
print('=' * 60)

class DualEncoderInheritanceModel(nn.Module):
    """
    """
    def __init__(self, bert_model_path, comp_vocab_size,
                 comp_dim=768, hidden_dim=768):
        super().__init__()

        self.bert = BertModel.from_pretrained(bert_model_path)
        for param in self.bert.pooler.parameters():
            param.requires_grad = False

        self.comp_embedding = nn.Embedding(comp_vocab_size, comp_dim, padding_idx=0)
        self.comp_proj = nn.Linear(comp_dim, hidden_dim)

        self.attn_query = nn.Parameter(torch.randn(hidden_dim))
        self.attn_key = nn.Linear(hidden_dim, hidden_dim)

        self.fusion_gate = nn.Linear(hidden_dim * 2, 1)

        self.compare_layer = nn.Sequential(
            nn.Linear(hidden_dim * 2, hidden_dim),
            nn.ReLU(),
            nn.Dropout(0.3),
            nn.Linear(hidden_dim, hidden_dim // 2),
            nn.ReLU(),
            nn.Dropout(0.3),
        )

        self.phonetic_head = nn.Linear(hidden_dim // 2, 1)
        self.semantic_head = nn.Linear(hidden_dim // 2, 1)

    def encode_single_char(self, bert_input_ids, attention_mask,
                           comp_ids, comp_mask):
        outputs = self.bert(bert_input_ids, attention_mask=attention_mask)
        h_bert = outputs.last_hidden_state[:, 0, :]  # [CLS]

        comp_emb = self.comp_embedding(comp_ids)
        comp_emb = self.comp_proj(comp_emb)

        comp_mask_3d = comp_mask.unsqueeze(-1)
        attn_keys = self.attn_key(comp_emb)
        attn_scores = torch.matmul(attn_keys, self.attn_query) / (comp_emb.size(-1) ** 0.5)
        attn_scores = attn_scores.masked_fill(comp_mask_3d.squeeze(-1) == 0, -1e9)
        attn_weights = F.softmax(attn_scores, dim=1).unsqueeze(-1)
        h_comp = (comp_emb * attn_weights).sum(dim=1)

        alpha = torch.sigmoid(self.fusion_gate(torch.cat([h_bert, h_comp], dim=-1)))
        h_fused = alpha * h_bert + (1 - alpha) * h_comp

        return h_fused, alpha

    def forward(self, batch):
        h_base, alpha_base = self.encode_single_char(
            batch['base_bert_input_ids'], batch['base_bert_attention_mask'],
            batch['base_comp_ids'], batch['base_comp_mask']
        )
        h_derived, alpha_derived = self.encode_single_char(
            batch['derived_bert_input_ids'], batch['derived_bert_attention_mask'],
            batch['derived_comp_ids'], batch['derived_comp_mask']
        )

        h_combined = torch.cat([h_base, h_derived], dim=-1)
        h_compare = self.compare_layer(h_combined)

        phonetic_logits = self.phonetic_head(h_compare).squeeze(-1)
        semantic_logits = self.semantic_head(h_compare).squeeze(-1)

        return {
            'phonetic_logits': phonetic_logits,
            'semantic_logits': semantic_logits,
            'h_base': h_base,
            'h_derived': h_derived,
            'alpha_base': alpha_base,
            'alpha_derived': alpha_derived,
        }

model = DualEncoderInheritanceModel(
    bert_model_path=MLM_OUTPUT_DIR,
    comp_vocab_size=COMP_VOCAB_SIZE,
).to(device)

n_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
print(f'Model parameters: {n_params:,}')


# ============================================================
# Cell 9: Training
# ============================================================
print('\n' + '=' * 60)
print('TRAINING')
print('=' * 60)

os.makedirs(OUTPUT_DIR, exist_ok=True)

optimizer = torch.optim.AdamW(model.parameters(), lr=2e-5, weight_decay=0.01)
phonetic_criterion = nn.BCEWithLogitsLoss()
semantic_criterion = nn.BCEWithLogitsLoss()

EPOCHS = 30

best_val_loss = float('inf')
history = {'train_loss': [], 'val_loss': [], 'val_phonetic_auc': [], 'val_semantic_auc': []}

for epoch in range(1, EPOCHS + 1):
    model.train()
    train_losses = []
    for batch in tqdm(train_loader, desc=f'Epoch {epoch}'):
        batch = {k: v.to(device) if isinstance(v, torch.Tensor) else v
                 for k, v in batch.items()}

        outputs = model(batch)

        p_loss = phonetic_criterion(outputs['phonetic_logits'], batch['phonetic_label'])
        s_loss = semantic_criterion(outputs['semantic_logits'], batch['semantic_label'])
        loss = p_loss + LAMBDA_SEMANTIC * s_loss

        optimizer.zero_grad()
        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
        optimizer.step()

        train_losses.append(loss.item())

    model.eval()
    val_losses = []
    all_phonetic_preds = []
    all_phonetic_labels = []
    all_semantic_preds = []
    all_semantic_labels = []

    with torch.no_grad():
        for batch in val_loader:
            batch = {k: v.to(device) if isinstance(v, torch.Tensor) else v
                     for k, v in batch.items()}
            outputs = model(batch)

            p_loss = phonetic_criterion(outputs['phonetic_logits'], batch['phonetic_label'])
            s_loss = semantic_criterion(outputs['semantic_logits'], batch['semantic_label'])
            loss = p_loss + LAMBDA_SEMANTIC * s_loss
            val_losses.append(loss.item())

            all_phonetic_preds.extend(torch.sigmoid(outputs['phonetic_logits']).cpu().numpy())
            all_phonetic_labels.extend(batch['phonetic_label'].cpu().numpy())
            all_semantic_preds.extend(torch.sigmoid(outputs['semantic_logits']).cpu().numpy())
            all_semantic_labels.extend(batch['semantic_label'].cpu().numpy())

    val_phonetic_auc = roc_auc_score(all_phonetic_labels, all_phonetic_preds)
    val_semantic_auc = roc_auc_score(all_semantic_labels, all_semantic_preds)

    avg_train_loss = np.mean(train_losses)
    avg_val_loss = np.mean(val_losses)

    history['train_loss'].append(avg_train_loss)
    history['val_loss'].append(avg_val_loss)
    history['val_phonetic_auc'].append(val_phonetic_auc)
    history['val_semantic_auc'].append(val_semantic_auc)

    print(f'Epoch {epoch:3d} | Train Loss: {avg_train_loss:.4f} | '
          f'Val Loss: {avg_val_loss:.4f} | '
          f'Phonetic AUC: {val_phonetic_auc:.4f} | '
          f'Semantic AUC: {val_semantic_auc:.4f}')

    if avg_val_loss < best_val_loss:
        best_val_loss = avg_val_loss
        torch.save(model.state_dict(), os.path.join(OUTPUT_DIR, 'best_model.pt'))
        print(f'  ✅ New best model saved')

print('\nTraining complete.')


# ============================================================
# Cell 10: Testing
# ============================================================
print('\n' + '=' * 60)
print('TESTING')
print('=' * 60)

model.load_state_dict(torch.load(os.path.join(OUTPUT_DIR, 'best_model.pt')))
model.eval()

all_phonetic_preds = []
all_phonetic_labels = []
all_semantic_preds = []
all_semantic_labels = []
all_alpha_base = []
all_alpha_derived = []

with torch.no_grad():
    for batch in test_loader:
        batch = {k: v.to(device) if isinstance(v, torch.Tensor) else v
                 for k, v in batch.items()}
        outputs = model(batch)

        all_phonetic_preds.extend(torch.sigmoid(outputs['phonetic_logits']).cpu().numpy())
        all_phonetic_labels.extend(batch['phonetic_label'].cpu().numpy())
        all_semantic_preds.extend(torch.sigmoid(outputs['semantic_logits']).cpu().numpy())
        all_semantic_labels.extend(batch['semantic_label'].cpu().numpy())
        all_alpha_base.extend(outputs['alpha_base'].cpu().numpy().flatten())
        all_alpha_derived.extend(outputs['alpha_derived'].cpu().numpy().flatten())

phonetic_auc = roc_auc_score(all_phonetic_labels, all_phonetic_preds)
phonetic_preds_binary = (np.array(all_phonetic_preds) > 0.5).astype(int)
phonetic_acc = accuracy_score(all_phonetic_labels, phonetic_preds_binary)
phonetic_f1 = f1_score(all_phonetic_labels, phonetic_preds_binary)

print(f'\n--- Phonetic Inheritance ---')
print(f'  AUC: {phonetic_auc:.4f}')
print(f'  Accuracy: {phonetic_acc:.4f}')
print(f'  F1: {phonetic_f1:.4f}')

semantic_auc = roc_auc_score(all_semantic_labels, all_semantic_preds)
semantic_preds_binary = (np.array(all_semantic_preds) > 0.5).astype(int)
semantic_acc = accuracy_score(all_semantic_labels, semantic_preds_binary)
semantic_f1 = f1_score(all_semantic_labels, semantic_preds_binary)

print(f'\n--- Semantic Inheritance ---')
print(f'  AUC: {semantic_auc:.4f}')
print(f'  Accuracy: {semantic_acc:.4f}')
print(f'  F1: {semantic_f1:.4f}')

print(f'\n--- Alpha (Fusion Gate) Analysis ---')
print(f'  Base char - mean α: {np.mean(all_alpha_base):.4f} (BERT weight)')
print(f'  Derived char - mean α: {np.mean(all_alpha_derived):.4f} (BERT weight)')
print(f'  α difference (derived - base): {np.mean(all_alpha_derived) - np.mean(all_alpha_base):.4f}')


# ============================================================
# Cell 11: Visualization
# ============================================================
print('\n' + '=' * 60)
print('VISUALIZATION')
print('=' * 60)

fig, axes = plt.subplots(1, 3, figsize=(16, 4))

axes[0].plot(history['train_loss'], label='Train', color='blue')
axes[0].plot(history['val_loss'], label='Val', color='red')
axes[0].set_title('Loss')
axes[0].set_xlabel('Epoch')
axes[0].legend()
axes[0].grid(True, alpha=0.3)

axes[1].plot(history['val_phonetic_auc'], label='Phonetic AUC', color='green')
axes[1].set_title('Phonetic AUC')
axes[1].set_xlabel('Epoch')
axes[1].legend()
axes[1].grid(True, alpha=0.3)

axes[2].plot(history['val_semantic_auc'], label='Semantic AUC', color='orange')
axes[2].set_title('Semantic AUC')
axes[2].set_xlabel('Epoch')
axes[2].legend()
axes[2].grid(True, alpha=0.3)

plt.tight_layout()
plt.savefig(os.path.join(OUTPUT_DIR, 'training_curves.png'), dpi=150)
plt.show()

fig, axes = plt.subplots(1, 2, figsize=(12, 5))

RocCurveDisplay.from_predictions(all_phonetic_labels, all_phonetic_preds, ax=axes[0])
axes[0].set_title(f'Phonetic Inheritance ROC (AUC={phonetic_auc:.4f})')

RocCurveDisplay.from_predictions(all_semantic_labels, all_semantic_preds, ax=axes[1])
axes[1].set_title(f'Semantic Inheritance ROC (AUC={semantic_auc:.4f})')

plt.tight_layout()
plt.savefig(os.path.join(OUTPUT_DIR, 'roc_curves.png'), dpi=150)
plt.show()

fig, axes = plt.subplots(1, 2, figsize=(12, 4))

axes[0].hist(all_alpha_base, bins=30, alpha=0.7, color='blue', edgecolor='white')
axes[0].axvline(np.mean(all_alpha_base), color='red', linestyle='--', label=f'Mean={np.mean(all_alpha_base):.3f}')
axes[0].set_title('α Distribution (Base Character)')
axes[0].set_xlabel('α (BERT weight)')
axes[0].legend()

axes[1].hist(all_alpha_derived, bins=30, alpha=0.7, color='green', edgecolor='white')
axes[1].axvline(np.mean(all_alpha_derived), color='red', linestyle='--', label=f'Mean={np.mean(all_alpha_derived):.3f}')
axes[1].set_title('α Distribution (Derived Character)')
axes[1].set_xlabel('α (BERT weight)')
axes[1].legend()

plt.tight_layout()
plt.savefig(os.path.join(OUTPUT_DIR, 'alpha_distribution.png'), dpi=150)
plt.show()

if len(all_phonetic_labels) == len(all_semantic_labels):
    fig, ax = plt.subplots(figsize=(8, 6))

    correct_both = (np.array(phonetic_preds_binary) == np.array(all_phonetic_labels)) & \
                   (np.array(semantic_preds_binary) == np.array(all_semantic_labels))
    wrong_both = ~correct_both

    colors = ['#2ecc71' if c else '#e74c3c' for c in correct_both]
    ax.scatter(all_phonetic_preds, all_semantic_preds, c=colors, alpha=0.5, s=20)
    ax.axhline(0.5, color='gray', linestyle='--', alpha=0.5)
    ax.axvline(0.5, color='gray', linestyle='--', alpha=0.5)
    ax.set_xlabel('Phonetic Inheritance Probability')
    ax.set_ylabel('Semantic Inheritance Probability')
    ax.set_title('Phonetic vs. Semantic Inheritance Predictions')
    ax.grid(True, alpha=0.3)

    plt.tight_layout()
    plt.savefig(os.path.join(OUTPUT_DIR, 'phonetic_vs_semantic.png'), dpi=150)
    plt.show()

print(f'\nAll figures saved to {OUTPUT_DIR}')

import json
from google.colab import drive

drive.mount('/content/drive')


with open(nb_path, 'r', encoding='utf-8') as f:
    nb = json.load(f)

code_cells = [c for c in nb['cells'] if c['cell_type'] == 'code']

lines = []
for i, cell in enumerate(code_cells[:10], start=1):   # Cell 1~10
    for out in cell.get('outputs', []):
        if 'text' in out:
            lines.append(''.join(out['text']))
        elif 'data' in out and 'text/plain' in out['data']:
            lines.append(''.join(out['data']['text/plain']))

out_path = '/content/drive/MyDrive/SCI_Journal/output.txt'
with open(out_path, 'w', encoding='utf-8') as f:
    f.write('\n'.join(lines))


!apt-get install -y graphviz
!pip install graphviz

# ============================================================
#   !apt-get install -y graphviz
#   !pip install graphviz
# ============================================================

import graphviz

# ============================================================
# ============================================================
dot = graphviz.Digraph('Tangut_Framework', format='png')

dot.attr(rankdir='TB', dpi='200', bgcolor='white',
         nodesep='0.5', ranksep='0.6')

C_CORPUS = '#D6EAF8'
C_DATA   = '#D5F5E3'
C_MODEL  = '#FDEBD0'
C_OUT    = '#F5B7B1'
EDGE     = '#2C3E50'

dot.attr('node', shape='box', style='rounded,filled', fontname='Helvetica',
         fontsize='11', color=EDGE, penwidth='1.5')

# ============================================================
# ============================================================
with dot.subgraph(name='cluster_corpus') as c:
    c.attr(label='Stage 1-3: LLM-Based Parallel Corpus Construction',
           labeljust='l', style='rounded,filled', fillcolor='#F4FAFE',
           color=EDGE, fontsize='12', fontname='Helvetica-Bold')

    c.node('src', 'Tangut Legal Texts\n(historical manuscripts)', fillcolor=C_CORPUS)
    c.node('s1', 'Stage 1: Dictionary Enhancement\n(expert verification)', fillcolor=C_CORPUS)
    c.node('s2', 'Stage 2: LLM-Agent Inference\n(Tang-Song legal priors)', fillcolor=C_CORPUS)
    c.node('s3', 'Stage 3: Two-Pass Verification\n(auto + human review)', fillcolor=C_CORPUS)
    c.node('corpus', 'Parallel Corpus\n(>10k sentence-pairs)', fillcolor='#AED6F1')

    c.edge('src', 's1')
    c.edge('s1', 's2')
    c.edge('s2', 's3')
    c.edge('s3', 'corpus')

# ============================================================
# ============================================================
with dot.subgraph(name='cluster_data') as d:
    d.attr(label='Inheritance Dataset Construction (Zero Annotation)',
           labeljust='l', style='rounded,filled', fillcolor='#F0FBEF',
           color=EDGE, fontsize='12', fontname='Helvetica-Bold')

    d.node('decomp', 'Radical Decomposition Table\n(5,910 valid, 9 phonetic classes)', fillcolor=C_DATA)

    d.node('enum', 'Base-Derived Pair Enumeration\n(component subset relation)', fillcolor=C_DATA)

    d.node('defenc', 'Definition Encoding\nvia Chinese BERT\n(cosine sim >= 0.5)', fillcolor=C_DATA)
    d.node('pairs', '12,150 Character Pairs\n[phonetic + semantic labels]', fillcolor='#82E0AA')

    d.edge('decomp', 'enum')
    d.edge('enum', 'pairs')
    d.edge('defenc', 'pairs')

dot.edge('corpus', 'defenc', style='dashed', constraint='false')

# ============================================================
# ============================================================
with dot.subgraph(name='cluster_model') as m:
    m.attr(label='Dual-Encoder Inheritance Model',
           labeljust='l', style='rounded,filled', fillcolor='#FFF8E7',
           color=EDGE, fontsize='12', fontname='Helvetica-Bold')

    m.node('bert', 'Shared BERT Encoder\n(Stage-1 MLM, vocab=27,956)',
           fillcolor='#FCF3CF', shape='component')

    m.node('b_char', 'Base Character', fillcolor=C_MODEL)
    m.node('b_bert', 'BERT Branch\n[CLS]', fillcolor=C_MODEL)
    m.node('b_comp', 'Component-Attention\nBranch', fillcolor=C_MODEL)
    m.node('b_gate', 'Fusion Gate\nalpha_base = 0.2488', fillcolor=C_MODEL)

    m.node('d_char', 'Derived Character', fillcolor=C_MODEL)
    m.node('d_bert', 'BERT Branch\n[CLS]', fillcolor=C_MODEL)
    m.node('d_comp', 'Component-Attention\nBranch', fillcolor=C_MODEL)
    m.node('d_gate', 'Fusion Gate\nalpha_derived = 0.2142', fillcolor=C_MODEL)

    m.node('compare', 'Compare Layer\n(MLP + ReLU + Dropout)', fillcolor='#F9E79F')
    m.node('pho', 'Phonetic Head\nAUC = 0.574', fillcolor=C_OUT)
    m.node('sem', 'Semantic Head\nAUC = 0.844, F1 = 0.9308', fillcolor=C_OUT)

    m.edge('b_char', 'b_comp')
    m.edge('b_bert', 'b_gate')
    m.edge('b_comp', 'b_gate')

    m.edge('d_char', 'd_comp')
    m.edge('d_bert', 'd_gate')
    m.edge('d_comp', 'd_gate')

    m.edge('bert', 'b_bert', style='dashed')
    m.edge('bert', 'd_bert', style='dashed')

    m.edge('b_gate', 'compare')
    m.edge('d_gate', 'compare')

    m.edge('compare', 'pho')
    m.edge('compare', 'sem')

dot.edge('pairs', 'b_char', style='dashed', constraint='false')
dot.edge('pairs', 'd_char', style='dashed', constraint='false')

dot.attr(label='Technical Route of Tangut Character Inheritance Analysis',
         labelloc='t', fontsize='16', fontname='Helvetica-Bold')

# ============================================================
# ============================================================
OUTPUT_DIR = '/content/drive/MyDrive/SCI_Journal/base_derived_inheritance'
dot.render(f'{OUTPUT_DIR}/technical_route_ortho', cleanup=True)

from IPython.display import Image, display
display(Image(filename=f'{OUTPUT_DIR}/technical_route_ortho.png'))
print(f'Saved to {OUTPUT_DIR}/technical_route_ortho.png')